#!/usr/bin/env bash

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland

export XCURSOR_SIZE=24
export MOZ_ENABLE_WAYLAND=1
export XDG_CURRENT_DESKTOP=Sway
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Sway
export QT_QPA_PLATFORMTHEME=qt5ct
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export SDL_VIDEODRIVER=wayland
export GTK_USE_PORTAL=0
export _JAVA_AWT_WM_NONREPARENTING=1
