# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_metrics\
$git_status\
$cmd_duration\
$fill\
$nodejs\
$golang\
$python\
$jobs $time\
$line_break\
$character
"""

# $os\

command_timeout = 3600000
scan_timeout = 500

[os]
disabled = false

[os.symbols]
Arch = "  "

[fill]
symbol = " "

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false

[directory]
style = "bold italic blue"
read_only = "  "
truncation_length = 10
truncate_to_repo = true

[character]
# Replace the "❯" symbol in the prompt with "➜"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = " "
style = "purple"
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)"
modified = "[${count}+](yellow)"
deleted =  "[${count}-](red)"
conflicted =  "[${count}~](red)"
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)"
staged = "[${count}+](green)"

[git_state]
style =	"bold red"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

[git_metrics]
disabled = false

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[nodejs]
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
format = 'via [$symbol($version )($mod_version )]($style)'

[python]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
