# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
# $username\
# $hostname\
# $time\

format = """
$directory\
$git_branch\
$git_metrics\
$git_state\
$git_status\
$c\
$cmake\
$cobol\
$crystal\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$cmd_duration\
$fill\
$jobs \
$line_break\
$character
"""

command_timeout = 500
scan_timeout = 30

[os]
disabled = false

[os.symbols]
Arch = "  "

[fill]
symbol = " "

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hostname]
ssh_only = false
format = 'on [$hostname](bold purple) '
trim_at = "."
disabled = false


[directory]
style = "bold italic cyan"
read_only = "  "
truncation_length = 10
truncate_to_repo = true

[character]
# Replace the "❯" symbol in the prompt with "➜"
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_branch]
symbol = " "
style = "bold bright-red"
format = "[$symbol$branch]($style)"

[git_status]
style = "bold red"
format = '([\[$all_status$ahead_behind\]]($style) )'
stashed = "[${count}*](green)"
modified = "[${count}+](yellow)"
deleted =  "[${count}-](red)"
conflicted =  "[${count}~](red)"
ahead = "⇡${count}"
behind = "⇣${count}"
untracked = "[${count}?](blue)"
staged = "[${count}+](green)"

[git_state]
style =	"bold yellow"
format = "[$state( $progress_current/$progress_total) ]($style)"
rebase = "rebase"
merge = "merge"
revert = "revert"
cherry_pick = "cherry"
bisect = "bisect"
am = "am"
am_or_rebase = "am/rebase"

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
format = '( \(([-$added]($added_style)) ([-$deleted]($deleted_style))\) )(bold white)'
disabled = false

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic bright-red"
format = ' took [$duration]($style)'

[memory_usage]
symbol = " "

[nodejs]
symbol = " "
format = "[$symbol($version )]($style)"

[golang]
symbol = " "
format = ' via [$symbol($version )($mod_version )]($style)'

[python]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"
