# Generated by hellwal

set wallpaper '%%wallpaper%%'

set background '%%background%%'
set foreground '%%foreground%%'
set cursor '%%cursor%%'
set border '%%border%%'

set color0 '%%color0.hex%%'
set color1 '%%color1.hex%%'
set color2 '%%color2.hex%%'
set color3 '%%color3.hex%%'
set color4 '%%color4.hex%%'
set color5 '%%color5.hex%%'
set color6 '%%color6.hex%%'
set color7 '%%color7.hex%%'
set color8 '%%color8.hex%%'
set color9 '%%color9.hex%%'
set color10 '%%color10.hex%%'
set color11 '%%color11.hex%%'
set color12 '%%color12.hex%%'
set color13 '%%color13.hex%%'
set color14 '%%color14.hex%%'
set color15 '%%color15.hex%%'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
